# Generated by Django 4.2.4 on 2023-08-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnownFace',
        ),
        migrations.AddField(
            model_name='user',
            name='face_descriptor',
            field=models.BinaryField(default=None),
        ),
    ]
